// FILE: background.js
// Initialize default settings when extension is installed
browser.runtime.onInstalled.addListener(() => {
const defaults = {
redirectUrl: "https://www.youtube.com/watch?v=NFWMSwfr4to",
blockedDomains: [
"pornhub.com",
"xvideos.com",
"xhamster.com",
"redtube.com",
"nhentai.com",
"nhentai.net",
"xnxx.com",
"rule34.xxx",
"pornfind.cc",
"xfantazy.com",
"nudevista.com",
"pornmd.com",
"rexxx.org",
"namethatpornstar.com",
"findtubes.com",
"ixxx.com",
"porndex.com",
"badjojo.com",
"ro89.com",
"rexxx.com",
"assoass.com",
"newbigtube.com",
"porn555.com",
"metaporn.com",
"nezha.life",
"18comic.vip",
"hanime.xyz",
"hanime1.me",
"animeporn.tube",
"cartoonpornvideos.com",
"pixiv.net/?return_to=%2Fcate_r18.php",
"hanime.tv",
"avbebe.com",
"furaffinity.net",
"hentaimama.io",
"sankakucomplex.com",
"hentaigasm.com",
"xanimu.com",
"hentai.tv",
"animeidhentai.com",
"ohentai.org",
"porcore.com",
"xmorex.com",
"muchohentai.com",
"underhentai.net",
"naughtymachinima.com",
"xanimeporn.com",
"hentaiworld.tv",
"hentaifreak.org",
"zzcartoon.com",
"hentai2w.com",
"hentaistream.com",
"utg12.com",
"hentaiplay.net",
"hanime1.com",
"dlsite.com",
"missav.ws",
"avple.tv",
"javmost.com",
"wnacg.com",
"eyny.com",
"artworks?mode=r18",
"jable.tv",
"adult.example"
],
blockedQueries: [
"hentai",
"nhentai",
"裏番",
"里番",
"中出",
"口交",
"エロ",
"工口",
"変態",
"へんたい",
"アヘ顏",
"素股",
"本番",
"絕頂",
"潮吹き",
"pron",
"porn",
"sex",
"色情",
"adult",
"ero",
"xxx",
"A片",
"18+",
"18X",
"R18",
"R-18"
],
enabled: true
};
browser.storage.sync.get(null, (items) => {
// only set defaults if not set
if (Object.keys(items).length === 0) {
browser.storage.sync.set(defaults);
}
});
});